on:
  push:
    branches:
      - '*'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Build Tusk
        run: cd tusk && cargo build
      - name: Build Tusk-Derive
        run: cd tusk-derive && cargo build
      - name: Run Clippy on Tusk
        run: cd tusk && cargo clippy -- -Dwarnings
      - name: Run Clippy on Tusk-Derive
        run: cd tusk-derive && cargo clippy -- -Dwarnings
