name: Publish to Crates.io
on:
  release:
    types: [published]
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Login to Cargo
        run: cargo login ${{ secrets.CARGO_KEY }}
      - name: Copy files into Crate
        run: |
          cp README.md tusk/README.md
          cp README.md tusk-derive/README.md
          cp LICENSE.txt tusk/LICENSE.txt
          cp LICENSE.txt tusk-derive/LICENSE.txt
      - name: Configure version
        run: |
          sed -i 's/0.0.0/${{github.ref_name}}/g' tusk/Cargo.toml
          sed -i 's/0.0.0/${{github.ref_name}}/g' tusk-derive/Cargo.toml
      - name: Publish Tusk
        run: cd tusk && cargo publish --allow-dirty
      - name: Publish Tusk-Derive
        run: cd tusk-derive && cargo publish --allow-dirty