name: Publish to Crates.io
on:
  push:
    branches:
      - main
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Login to Cargo
        run: cargo login ${{ secrets.CARGO_KEY }}
      - name: Publish Tusk
        run: cd tusk && cargo publish
      - name: Publish Tusk-Derive
        run: cd tusk-derive && cargo publish